### ISSUE TITLE
mockedAjaxCalls Doesn't Seem to Be Working

### ISSUE THREAD

**Issue by machineghost** [jakerella/jquery-mockjax#135]
Maybe I'm misunderstanding how things are supposed to work, but when I do:

```
$.mockjax({url:  'localhost/foo/', responseText: ''});
console.log($.mockjax.mockedAjaxCalls());
```

I see `[]`, not `[{url:  'localhost/foo/', responseText: ''}]` (or some other representation of my mocked response) as I would have expected.

Am I using mockedAjaxCalls incorrectly, or is this behavior a bug?

**Comment by iamrandys** [comment]
I ran across the same issue.  I really need to see if there are any loaded.  So I can display in the UI if there are any loaded or not.  This was misleading.

Is there any way to get a count of active mocks?

**Comment by jakerella** [comment]
@iamrandys I suppose I can see how the name of the method could be misleading, but we can't go changing it now, this has been implemented for quite some time. I'm not exactly sure what you mean by "a count of active mocks" because a single mock handler can mock out (potentially) an infinite number of ajax calls. If you mean "how many times has an ajax call been mocked" then you can use `mockedAjaxCalls()` and get the length. If you mean, "how many mock handlers have been created" then no, there is not currently a way to do that.

Since either of those use cases is outside of the scope of the OP's issue, you should probably either submit a new issue with the specific feature request, or a PR with the functionality you want!

**Comment by iamrandys** [comment]
Yes, I was needing to know "how many mock handlers have been created".  I was able to get around this by doing something like:

```
var mocksEnabled = ($.mockjax.handler(0) !== undefined);
```

Thanks for the feedback!

Oh and we might want to update the documentation. "Returns an array of all mocked ajax calls" makes me think it will return all of the handlers.

**Comment by jakerella** [comment]
You are free to submit a PR for the documentation, but I have to say, to me that phrase means exactly what I intended. A "call" is exactly that, a call to the `$.ajax()` method that was mocked out. A handler is just that, a handler (and not a "call"). If you have a better idea for the language feel free to submit the PR. Please also open up that other issue (feature request).

**Comment by iamrandys** [comment]
Ah, I can see that now.  I wasn't familiar enough with the project to see the difference between the two.

I think adding the past tense "were" will make it clearer.  I'll create a PR.

Form:
Returns an array of all mocked ajax calls with each entry being the request settings object as passed into the $.mockjax() function

To something like:
Returns an array of calls that were intercepted by mockjax, with each entry being the request settings object as passed into the $.mockjax() function
