### ISSUE TITLE
mockjax does not return "random data"

### ISSUE THREAD

**Issue by freestyle21** [jakerella/jquery-mockjax#222]
when I code:

        $.mockjax({
          url: '/activity/detail',
          responseText: {
            status: 'online|offline'
        });

I want return random status"online" or "offline"

**Comment by jakerella** [comment]
Random data return is not a feature that we currently support. That said, you're welcome to submit a PR!

**Comment by prantlf** [comment]
Why not using the response function callback?

    $.mockjax({
      url: '/activity/detail',
      response: function () {
        this.responseText = {
          status: _.random(0, 1) ? 'online' : 'offline'
        };
      }
    });

If the response gets complicated, you probably won't be able to use a constant object literal anyway.

You can use any randomizing function; I used [random from Underscore.js](http://underscorejs.org/#random).

**Comment by jakerella** [comment]
+1 for a custom `response()` function. Honestly, I don't see this being a feature we implement ourselves, so going to close for now.

**Comment by freestyle21** [comment]
response() function can resolve the example I give.

But in our project random data is so large that response() func cannot handle well.

I has used the same platform like mockjax in my company, so I make some suggestions, ^_^

Thank you all.

**Comment by reinrl** [comment]
@jakerella - I have a page which contains a large data grid (using the jQuery DataTables plugin), and I wanted to simulate getting random errors when performing an action (e.g., delete a record in the table). Hooking into the response meant that once the page loaded/that the mock was built, I always got the same response for every delete call (e.g., I could set a random status value - 200, 400, 500, etc. - but that "random" response was always the same for every call on that page, instead of being a random status between individual calls once the page was loaded). I customized mockjax locally to support this within the plugin (see below), is there an appetite for a pull request with something like this?

```
function getRandomInteger(min, max) {
	min = Math.ceil(min);
	max = Math.floor(max);
	// get a random integer between two values, inclusive
	return Math.floor(Math.random() * (max - min + 1)) + min;
}
```

then replace this:
```
if( typeof mockHandler.status === 'number' || typeof mockHandler.status === 'string' ) {
	this.status = mockHandler.status;
}
```

with this:
```
if( typeof mockHandler.status === 'number' || typeof mockHandler.status === 'string' ) {
	var arrStatus = (typeof mockHandler.status === 'string' ? 
		mockHandler.status.replace(/\s+/g, '').split('||') : 
		mockHandler.status.toString().split('||'));
	var idxStatus = getRandomInteger(0,arrStatus.length-1);
	this.status = arrStatus[idxStatus];
}
```

**Comment by jakerella** [comment]
I understand the business case for this, but what I don't understand is why the custom `response` function doesn't solve the issue. Why not just do this:

```
let possibleStatusCodes = [200, 400, 500];
$.mockjax({
  url: '*/Groups/*',
  type: 'DELTE',
  response: function () {
    this.status = possibleStatusCodes[_.random(0, 2)]
    // ...
  }
});
```

That `response` function is evaluated _every_ time the mock is hit, not once at application startup. As for the PR, I'm not opposed to this as a feature, but it just seems like what I have above solves that a bit easier.

**Comment by reinrl** [comment]
@jakerella - I created this patch because I am not seeing  what you describe above. When I put the randomness in the response function (either directly, or have a line line this.status = getRandomResponse();, which in turn points to a common function on my own), I see that line get called once when the mockjax configuration is loaded - meaning that subsequent calls to the same endpoint (see my "delete groups" example in the comment above) always get the same response as the first call. When I move the randomness into the plugin itself (and in turn, randomly grab from the provided list of responses), I see the random response generator get called with each and every hit. Am I missing something about the evaluation of the response function, or is it not functioning the way that it was intended?

**Comment by jakerella** [comment]
Sorry, but you must be missing something. Here is a JSBin to show what I mean (hit the "Run" button in the top right). The "processing response" console message appears 3 times in the output... once per hit to the mock. That function is NOT called at application startup at all.

https://jsbin.com/lipaqomocu/edit?html,js,console

**Comment by reinrl** [comment]
I see exactly what I was missing now. While at first glance it seemed like we were saying the same thing...there was a key miss on my part. Rather than setting the status within a response function (which does indeed get reevaluated every time), I was trying to randomly set a specific status within the status attribute (see my example above). This in fact is only set up once, and led to me searching for a workaround. So really, my patch was more about my way of setting up the status vs. yours - and ultimately, the decision for inclusion seems to be more about the recommended best practices for the plugin. Is attaching status directly to the instantiation (vs. setting it up in the response) ideal, are both useful, or is steering people the direction of the response a better/more flexible way? If the third, I am more than happy to add an example of this whole mess into the documentation.

**Comment by jakerella** [comment]
I think having multiple ways to accomplish a task is good. Let's continue the discussion in your PR and not overload this issue.
