### ISSUE TITLE
Access request.body, inside the mock function

### ISSUE THREAD

**Issue by madhavan020985** [jakerella/jquery-mockjax#264]
````javascript
$.mockjax(function( requestSettings ) {
  return {
    response::: 
}
````
I see, the above snippet enables the tester to access the request headers. 
On the same lines, i am interested in getting the request body as a parsed JS object. I am not seeing any hints about request.body in github README page.
Is that supported by mockjax?

**Comment by jakerella** [comment]
In your case, the ajax call has been intercepted before an HTTP request has even been composed. You will not have access to a request body because there is no request (yet). Instead, you will have access to the full settings that the calling code sent in. In particular, you probably want to access the `data` attribute:

```js
$.mockjax( function( settings ) {
    
    console.log( settings.data );  // matches what is sent in through $.ajax()
    
    return {
        response: function() {
            this.status = 200;
            this.responseText = { "the": "answer" };
        }
    };
});

$.ajax({
    type: 'POST',
    url: '/foo/bar',
    dataType: 'json',
    data: { "foo": "bar" },
    // ...
});
```

**Comment by jakerella** [comment]
Hope the answer helped! Let me know if you have any other questions, happy to help.

**Comment by madhavan020985** [comment]
it helped... added those two lines of my stuff to README.md....
