### ISSUE TITLE
How to mock jqery ajax call which used deffered object ?

### ISSUE THREAD

**Issue by wtercha** [jakerella/jquery-mockjax#270]
Hi,

I want to mock sth like this function used mockjax:

get= function(id) {
    var deferred = $.Deferred();
    $.ajax({
        type : 'GET',
        url : '/json/' + id,
        dataType : 'jsonp',
        crossDomain:true,
        success : function(data) {
            deferred.resolve(data); 
        },
        error : function(data) {
            deferred.reject(data);
        },
    });
    return deferred.promise();
};

I called my method  in other .js file like this get(2).then(function(response){...})

I tried mock sth like this:

 $.mockjax({
                url: "/json/2",
                response: function(settings) {
                    this.responseText ={"status":"ok","data":[]};
                }
             });

and I get error: 

GET file:///D:/json/2?callback=jQuery1111047122289054095745_1445082050594&_=1445082050595 net::ERR_FILE_NOT_FOUND.

Can anyone help me resolve this?

**Comment by jakerella** [comment]
Did you know that as of jQuery 1.5 the `ajax()` method implements promises by default? Why not use that?

```js
$.ajax({
  url : '/json/' + id
}).done(function( data ) {
    // ... do whatever you need to with the data
});
```

If you use promises like this then mockjax will work just fine. Your use case should also work, but I know there was some issue with cross domain requests (see #136), so this may not work. If not, you may have to wait for that bug to be fixed for full cross domain support. That said, looking at your ajax call, it does not look like it is actually cross domain since the URL is `/json/2` ... where is the other domain?

**Comment by jakerella** [comment]
Closing for no response.
