### ISSUE TITLE
How to validate request JSON payload?

### ISSUE THREAD

**Issue by koorgoo** [jakerella/jquery-mockjax#290]
I have not found in README how to validate JSON data.
The problem is the same object may have several JSON representations.

```
var obj = {one: 1, two: 2};
var json1 = '{"one": 1, "two": 2}';
var json2 = '{"two": 2, "one": 1}';
```

$.mockjax allow to validate request data with `data` parameter. But due to several possible JSON representations the validation may fail (and it fails in my tests from time to time).

```
$.mockjax({
  ...
  data: JSON.stringify(expectedObj),
  ...
});
```

Also another options is available that seems hacky to me - use `response` function parameter. It breaks the Single Responsibility Principle - response functions becomes responsible for request validation.

```
$.mockjax({
  ...
  response: function(settings) {
    expect(JSON.parse(settings.data)).to.eql(expectedObj);
    this.responseText = ...
  },
  ...
});
```

Please, give me a piece of advice how to test request JSON payload with $.mockjax properly?

**Comment by jakerella** [comment]
Great question, and you are correct in that we only verify the string value - because that's what will eventually get sent over HTTP (not objects). One thing we could do is check the `contentType` header during [mock handler inspection](https://github.com/jakerella/jquery-mockjax/blob/master/src/jquery.mockjax.js#L196) and if it's JSON we could do a more extensive check on the data. The problem with that approach is that jQuery has no way to deeply compare two objects, thus we'd have to either (a) pull in another library or (b) write a deep object comparison ourselves.

I'm not opposed to (b), but I don't think (a) is appropriate. So... I'll flip this into a feature request, but I'm not sure how we'll proceed just yet. Suggestions are welcome!

**Comment by koorgoo** [comment]
I suggest another option to delegate data validation to developers. I mean to allow `data` parameter to be a function that must return `true` when data is valid. The developer will be responsible for validation and used libraries accordingly. Better to see once:

```
$.mockjax({
  ...
  data: function(data) {
    data = JSON.parse(data);

    // Use any testing framework or library to check equality.
    expect(data).to.eql(expectedObj);    // Chai
    assert.deepEqual(data, expectedObj); // QUnit
    var res = equal(data, expectedObj);  // deep-equal NPM package

    return true;
  },
  ...
});
```

**Comment by koorgoo** [comment]
I don't think that any comparison with Angular is permitted, but this is how [when() method](https://code.angularjs.org/1.5.5/docs/api/ngMock/service/$httpBackend#when) of $httpBackend (mock for testing) works - `data` is an optional parameter allow to be a function.

**Comment by jakerella** [comment]
Hmm, yeah, that is definitely a simple option. I'm willing to do that now and consider some more involved options for a future release. Not sure when I'll get to that, but if you want to submit a PR for this I'll definitely consider it!

Otherwise I'll try to tackle it some time in the next couple months, but it might not make the 2.2.0 release (which I hope to have out in the next couple weeks.

**Comment by koorgoo** [comment]
Turned out to be easy as a pie.

**Comment by koorgoo** [comment]
Thanks for discussion!
