### ISSUE TITLE
mockjax syntax error

### ISSUE THREAD

**Issue by brighten01** [jakerella/jquery-mockjax#299]
it is a bad thing for mockjax,   when i use it and based for  jquery 1.11.min.js  and  jquery.mockjax.js  , It  tell me  syntax error ,   this is code here:
error:
```
SyntaxError: missing ] after element list
url:"http://myweb.cn/testindex.php",
```
so lazy mans you are  ,
plese tellme why ! thank you .

**Comment by jakerella** [comment]
I'm assuming you closed this because you realized there are no syntax errors in the code. That's why we have automated tests that show you the status on the README in this repo. I really don't appreciate being called "lazy". Comparing our open source contributions, I'm fairly certain that "lazy" is just about the opposite of my track record on GitHub.

The next time you post an issue on a repository, please try to be more considerate and at least investigate what the real source of the issue is.
