### ISSUE TITLE
Cross-domain Request ("XDR")  can't be 'hijacked' 

### ISSUE THREAD

**Issue by rpdg** [jakerella/jquery-mockjax#306]
`jquery-mockajax@2.2.0` and `jQuery 3.1.1`

`
$.mockjaxSettings.namespace = 'http://10.223.126.249:8080/api/';
$.mockjax({
      url: "roles",
    responseText: {}
});
`

**Comment by jakerella** [comment]
This looks like the beginnings of a bug submission. Can you please describe the issue in a little more detail? Specifically I'd need to see a bit more of your code, a description of what you expected to happen, and what actually happened. Thanks!

**Comment by tomeara** [comment]
I think I might be having the same issue as @rpdg did. I've created a failing test, and I've looked into how to fix, but I'd like to discuss the problem and what I've been looking into as an approach.

Here's the failing test that I put together by copying an existing one:

```javascript
t('should pass url to response settings using http://', function(assert) {
	var done = assert.async();

	$.mockjaxSettings.namespace = 'http://localhost:4000';

	$.mockjax({
		url: 'myservice',
		response: function(settings) {
			assert.equal(settings.url, 'http://localhost:4000/myservice');
		}
	});

	$.ajax({
		url: 'http://localhost:4000/myservice',
		error: qunit.noErrorCallbackExpected,
		complete: function(xhr) {
			assert.equal(xhr.status, 200, 'Response was successful');
			done();
		}
	});
});
```
It looks like the issue is on  https://github.com/jakerella/jquery-mockjax/blob/master/src/jquery.mockjax.js#L170. The regex for the replace is removing all repeated `/` characters. I've looked into how to fix, and if JavaScript had negative lookbehinds we'd be able to do something like this: `namespacedUrl = namespacedUrl.replace(/(?<!:)(\/+)/g, '/')`. Instead I'd probably want to create a function that reverses the string, replaces any `/` and reverses it back, but I'm not sure if having `http://` in the namespace is something that the maintainers would want.

* Is `http://` and `https://` something that you'd like added to the namespace?
* If so, how does the solution sound for using a function to replace `/` only when not prefaced with a `:` by reversing the string?

**Comment by jakerella** [comment]
Thanks for looking into this! I think there is a much simpler solution. The reason line 170 exists is because people would add a namespace ending in a slash, then _also_ use a slash in their mocks (i.e. `http://localhost:8080/api/` and then `/foo` for the mocked endpoint). This results in a double slash, which would fail to be mocked out. So maybe the solution is that on 170 we actually just check if the last character in the namespace is a `/` and if so, ensure the first character of the `handler.url` is _not also_ a slash.

**Comment by tomeara** [comment]
Ok perfect! In that case, how's this solution:
```javascript
if (!!namespace) {
	var namespacedUrl = [
		namespacenamespace.replace(/(\/+)$/, ''),
		handler.url.replace(/^(\/+)/, '')
	].join('/');
	handler.url = namespacedUrl;
}
```
Putting together a PR now...

**Comment by jakerella** [comment]
looks good to me... I'll take a look at the PR this weekend
