### ISSUE TITLE
no response returned

### ISSUE THREAD

**Issue by zzzgit** [jakerella/jquery-mockjax#307]
```javascript
mockjax({
    url: '/resource',
    responseText: 'content'
});

function getResource(cb) {
    jquery.ajax({
        url: '/resource',
        success: cb,
        error: cb
    });
}

function cb(response){
    window.alert(response);  //undefined
}
```

why it is undefined?

**Comment by jakerella** [comment]
Show me where you call the `getResource()` function... but if you call it like: `getResource(cb)` then I'm not sure. I would need to see more context as this simple example works when I code it.

**Comment by zzzgit** [comment]
i called `getResource` just follow the snippet above
and more info,i installed this plugin in `npm`,and imported it by `ES6` syntax

**Comment by zzzgit** [comment]
i've wrote a jQuery plugin which has main API of this plugin.
cause of this plugin doesn't work on my computer
hehe

**Comment by jakerella** [comment]
...

The plugin works fine, if you can't show me the actual code then I can't help you. The code snippet you have works fine for me if called correctly. The plugin also works fine as an npm install and with ES6 imports (we have tests for this). If you want help debugging then post a more complete code sample. I'm happy to help! For now I'm closing since there is not enough info to debug.
