### ISSUE TITLE
$.ajax call's success callback receives undefined - jQuery 3.3.1

### ISSUE THREAD

**Issue by magnusram05** [jakerella/jquery-mockjax#345]
$.ajax call's success callback receives undefined.

jQuery 3.3.1, mockjax: 1.6.2
Chrome Version 70.0.3538.102 (Official Build) (64-bit)

Mock:
```
$.mockjax({
			  url: "reference",
			  contentType: "text/plain",
			  response: function() {
			  	 this.responseText = 'Reference';
			    }
			});
```
Caller:
```
$.ajax({
				url: "reference",
				success: function(response){ //undefined
					console.log(response.responseText);
				},
				error: function(error){ //undefined
					console.log(response.responseText);
				}
			})
```

**Comment by jakerella** [comment]
You don't actually get the full response object in jQuery's success callback, you only get the response data (either the text for `plain/text`, as in your case, or an object in the case of `json`). To get the full response object you will need to use a [jquery ajax `complete` callback](http://api.jquery.com/jquery.ajax/). As such, there is no `responseText` property since it is just a string, not an object.

Here is a test showing that this is working as expected. Let me know if you have any questions!

```
t('Bug #345: undefined response object using response function', function(assert) {
    var done = assert.async();

	$.mockjax({
		url: 'reference',
		contentType: 'text/plain',
		response: function() {
			this.responseText = 'this is the response data';
		}
	});

	$.ajax(undefined, {
		url: 'reference',
		success: function(response) {
			assert.deepEqual(response, 'this is the response data');
			assert.strictEqual(typeof(response.responseText), 'undefined');
		},
		error: function() { assert.ok(false); /* this is bad */ },
		complete: done
	});
});
```

**Comment by magnusram05** [comment]
'response' itself was undefined in my case..but if ajax's complete callback is working then I am fine. Thanks.
