### ISSUE TITLE
responseText is assumed to be JSON with JSONP requests

### ISSUE THREAD

**Issue by JohnKurlak** [jakerella/jquery-mockjax#86]
See the following JSBin:
http://jsbin.com/cojacalome/1/edit?html,js,output

Notice that the first request succeeds, but the second one fails.  The problem is that mockjax is expecting responseText to be a JSON object when dataType is set to 'jsonp'.  However, it is possible to pass data of any type (i.e., string) into a JSONP callback.

**Comment by jakerella** [comment]
I've been looking into this, and actually, that example is operating as expected.

The result data from a jsonp call _must_ include a function to execute, that's how jsonp works. For some reason, historically Mockjax has allowed objects in the `responseText` field and done some work to pretend like that had come from a callback, but really, that's not how it's supposed to work. If you actually tried to do a *real* jsonp call to a server that only returned "Howdy" in the response the result would basically be nothing since there is no callback function to execute.

As such, I'm going to close this bug for now. If there is a valid use case I'm happy to explore it.

**Comment by JohnKurlak** [comment]
@jakerella You don't seem to understand.  When you make a JSONP request through jQuery, it adds a <script> tag with the src set to the page that serves the JSONP request.  That page outputs JavaScript code that calls some callback.  E.g.: It adds: <script src="http://some.server.com/greet?user=john&callback=greeting"></script>.  The JavaScript response might be: greeting('Howdy');  Or it might be: greeting({ message: 'Howdy' });.  Either is valid!  When the <script> tag is added, the greeting() function, which jQuery will define, will be called.  jQuery then extracts whatever response value was passed to the greeting() function.  In this case, the response value could be a string, an object,... anything.  Mockjax should support any kind of response text.

**Comment by JohnKurlak** [comment]
Also, the JSFiddle seems to be broken, so here's the issue in JSBin (Ctrl+Enter to run): http://jsbin.com/cojacalome/1/edit?html,js,output

**Comment by jakerella** [comment]
@JohnKurlak I do understand very well how jsonp works. And I think the difference in our thoughts stems from the intended use of the `responseText` setting of the `$.mockjax()` call. While jQuery will dynamically create a globally accessible function for the other server to call, the remote server must still return _that exact function_ in the response body of the `<script>` tag HTTP call. In the case you have suggested, our "remote server" has given us back "Howdy" as the entire response body, which is not a valid jsonp response.

Mockjax makes an exception for JavaScript objects in the `responseText` field: it stringifies them and uses that as the return data for the ajax call. But note that in your example there is no dynamic jQuery wrapper function created. The "server response" in this case is whatever you put in the `responseText` field. If you actually fill the `responseText` field with `"foo('bar')"` and then actually define a global `foo` function it will be called with the `bar` data.

Okay, now with that said, what I really need to see is the source code call you're trying to mock, what the server returns for that call, what jQuery returns normally (on success), and then exactly what you expect to occur in the mocking. Otherwise, this is still expected (if not totally desired) functionality.

**Comment by JohnKurlak** [comment]
@jakerella I wasn't saying that you don't understand how JSONP works.  I was saying you don't understand what the issue I filed is.  I don't disagree that the remote server must still return that exact function in the response body of the script tag HTTP call.  We are in agreement there.  I'm also NOT suggesting that the server returns "Howdy" as the entire response body.  I am suggesting that the server returns callback("Howdy");, which is a valid JSONP response.

The responseText field in the case of JSONP should not specify the exact value that is returned from the server.  Instead, it should specify the value that gets passed to the success callback of the jQuery ajax() call.  Currently, the expected behavior I describe is exactly how Mockjax works when responseText is a JSON object.  I don't understand why Mockjax makes an exception for JS objects only.  Whether your server response calls the callback with a JS object, number, or text value is irrelevant.  All should produce the same behavior.  Since we're mocking out the JSONP request, we don't care about actually creating a callback that is called.  All we care about is that the success handler of our $.ajax() call receives the value that we specify as "responseText".

**Comment by JohnKurlak** [comment]
Here's an example: http://jsbin.com/moqiwaseko/1/edit?js,output

Uncomment the mockjax code to see the expected behavior.

**Comment by jakerella** [comment]
Let me take another look at the source... the fact is, even for JSON objects we are _not_ generating a `jQuery4289347923()` sort of function. We seem to be handling JSON data in `responseText` specially... honestly, I'm not sure how a Number would work either, but that's not the point.

**Comment by JohnKurlak** [comment]
The issue is with this line:

    $.globalEval( '(' + mockHandler.responseText + ')');

It should surround the value with quotes if the type of responseText is a string.

**Comment by jakerella** [comment]
The reason that line is there is that if the `responseText` is a function call (as it would be in an actual jsonp request, or like it is when we use a proxy), then the function returned in the response must be evaluated (executed) in the global scope. As you can see, we do some weird handling of different cases in that function and, honestly, it doesn't make much sens to me why. This may be a case where we need to step back and re-evaluate how we handle jsonp entirely and simplify the process.

**Comment by JohnKurlak** [comment]
Suppose responseText is a function call, e.g.:

    someFunctionIDefined('howdy')

Then it will call my function, which is great, but the success handler will be called with:

    someFunctionIDefined('howdy')

Instead of:

    howdy

It seems like the library has two different meanings for what `responseText` is (in the context of JSONP requests).  The first meaning is the value that comes back from the server, and the second meaning is the value with which the success callback is resolved.  In the case of JSONP, these are two different values.  In the case of everything else that isn't JSONP, these are the same value.

What I don't understand is why anyone would care to mock out the value that comes back from the server.

**Comment by jakerella** [comment]
They would want to mock what comes back from the server to test that their code handles it properly... If you specify a callback function, then you probably want to test that that callback function handles the jsonp response correctly, and that the whole round trip works as expected.

**Comment by JohnKurlak** [comment]
If you make your JSONP requests with jQuery, you don't write a callback function.  jQuery does that for you.

**Comment by jakerella** [comment]
Yeah, you can specify the callback. And if you do jQuery _does not_ send it's own generated jQuery callback to the remote server (see the [source here](https://github.com/jquery/jquery/blob/1.11-stable/src/ajax/jsonp.js#L34-L43)). The URL it sends to the remote server will use the callback function name you provide, and that is the use case we must handle with the `$.globalEval()` so that a custom callback function can be executed.

**Comment by JohnKurlak** [comment]
Yes, the URL it sends uses the callback function *name* you provide, but the function *implementation* is one that it provides.  See: https://github.com/jquery/jquery/blob/1.11-stable/src/ajax/jsonp.js#L58-60

**Comment by jakerella** [comment]
Hmm... perhaps not, but then the field is misleading, no? I mean... `responseText` is used as the raw response body in other mocks, and not having it be that seems misleading. I think we need to allow either situation, but not sure how yet.

**Comment by JohnKurlak** [comment]
I agree that the meaning of `responseText` in the context of JSONP is ambiguous.  It will be up to the documentation to make that clear.  If you want to support either situation, that's fine.  The current implementation of mockjax supports neither situation correctly (it does a hybrid of the two), and that's why I filed the issue (I was unable to mock out a JSONP request that I was making and have the success callback fire with the correct value).

My preference would be to handle JSONP mocking just like jQuery handles JSONP.

With jQuery, when you call `$.ajax` with `dataType: 'jsonp'`, you're saying, "Please take care of all the dirty implementation details of JSONP for me. I want you to do all the heavy lifting so I don't have to think about writing boilerplate code with callbacks."

With mockjax, when you call `$.mockjax` with `dataType: 'jsonp'`, it should be the same way.  I don't want to worry about callbacks and whatnot.  I just want to specify the mock response that my success handler is called with.  If I find a rare scenario (I can't think of one right now) where I want to mock the raw server response, then I can just leave off `dataType: 'jsonp'` and treat it as a regular mockjax request.

Thoughts?

**Comment by jakerella** [comment]
Hmm... all good points, I am leaning more toward the first option, with proper documentation on how to implement the raw response if needed.

@dcneiner Any input on this one?

I think this issue requires a more thoughtful refactoring, and I'm going to push it back past the 2.0.0 release. I need to get some of these other updates out and I don't want this holding it back, even if it is a (currently) broken implementation. I'll target it for 2.0.1 though as a bug fix.

**Comment by JohnKurlak** [comment]
Thanks for looking into this!

**Comment by jakerella** [comment]
This issue should be resolved. The tweak suggested above by @JohnKurlak was part of the solution, but we also had a bug in how the jsonp callback was being generated. The JSBin referenced above won't work because of the change of file structure in `master`, but this new JSBin does work, and nearly mirrors his code (although I changed it to use `console.log()` versus `alert()`).

http://jsbin.com/qexumicace/edit?html,js,console
